### ISSUE TITLE
Question about quaternion epsilon

### ISSUE THREAD

**Issue by gdevillele** [cubzh/cubzh#5]
<img width="673" alt="Screenshot 2022-09-22 at 22 39 01" src="https://user-images.githubusercontent.com/939999/191846647-b063846b-3431-4add-83b9-783a2efae7c6.png">

https://github.com/cubzh/cubzh/blob/main/core/quaternion.c#L19

**Comment by ArthurVoxowl** [comment]
Because it is zero doesn't mean it should be eliminated. Its function is to control how often quaternion normalization occurs. A value of zero means we want normalization to occur every time. As the comment states, we could choose to increase it slightly to reduce normalization frequency at the cost of accuracy. It's another lever that we can move along the line of accuracy vs. performance
